[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["PigeonsHouse"]

[workspace]
resolver = "2"
members = ["vsml_core", "vsml_parser"]

[workspace.dependencies]
vsml_core = { path = "vsml_core" }
vsml_parser = { path = "vsml_parser" }
cssparser = "0.34.0"
roxmltree = "0.20.0"
thiserror = "2.0.3"
