[package]
name = "vsml_parser"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
vsml_ast.workspace = true
vsml_core.workspace = true
nom.workspace = true
regex.workspace = true
roxmltree.workspace = true
thiserror.workspace = true

[dev-dependencies]
mockall.workspace = true
