[package]
name = "vsml_parser"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }

[dependencies]
vsml_core = { workspace = true }
cssparser = { workspace = true }
roxmltree = { workspace = true }
thiserror = { workspace = true }
