[package]
name = "vsml_encoder"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
vsml_common_audio.workspace = true
vsml_common_image.workspace = true
vsml_core.workspace = true
hound.workspace = true
temp-dir.workspace = true
